/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.6/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    java
    application
    checkstyle
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")
}

application {
    // Define the main class for the application.
    mainClass.set("btosystem.App")
}

tasks.withType<Javadoc> {
    options {
        this as StandardJavadocDocletOptions
        // addStringOption("Xdoclint:none", "-quiet") // Disables strict linting
        addBooleanOption("author", true) // Includes @author tags
        addBooleanOption("version", true) // Includes @version tags
    }
    setDestinationDir(file("../docs/javadoc")) // Output directory
}

checkstyle {
    toolVersion = "10.23.0" 
    configFile = rootProject.file("app/config/checkstyle/google_checks.xml")
    isIgnoreFailures = false 
}

tasks.withType<Checkstyle> {
    reports {
        html.outputLocation.set(file("../docs/checkstyle/main.html"))
    }
    ignoreFailures = false
}

tasks.build {
    dependsOn(tasks.checkstyleMain, tasks.javadoc)
}